### ISSUE TITLE
[rocks] log fails

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1181]
Branch `lakefs://foo/trunk` is the default branch and has 2 commits.  Logging fails:

```log
DEBUG  [2021-01-12T10:10:16+02:00]gateway/middleware.go:98 gateway.EnrichWithOperation.func1.1 performing S3 action                          action=list_objects message_type=action
INFO   [2021-01-12T10:10:16+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="125.958µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:16+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="231.57µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:16+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="267.434µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:16+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="315.704µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
DEBUG  [2021-01-12T10:10:16+02:00]httputil/logging.go:77 httputil.DebugLoggingMiddleware.func1 HTTP call ended                               host="s3.local.lakefs.io:8000" list_type=v2 method=GET path="/foo?list-type=2&prefix=trunk%2F&delimiter=%2F&encoding-type=url" repository=foo request_id=40c4cb6e-a144-4281-a9d2-564b510e539f sent_bytes=617 service_name=s3_gateway status_code=200 took=1.367416ms user=me
DEBUG  [2021-01-12T10:10:27+02:00]api/api_controller.go:96 api.(*Dependencies).LogAction performing API action                         action=create_commit host="localhost:8000" message_type=action method=POST path=/api/v1/repositories/foo/branches/trunk/commits request_id=cfc2eec1-b790-43a0-9108-a6ee770cd0a7 service_name=rest_api user=me
INFO   [2021-01-12T10:10:27+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="85.859µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:27+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="129.592µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:27+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="150.52µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-12T10:10:27+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-c235a04f-96d6-4ab1-bf7d-96471d0d0178  1001]" duration="173.772µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
DEBUG  [2021-01-12T10:10:27+02:00]httputil/logging.go:77 httputil.DebugLoggingMiddleware.func1 HTTP call ended                               host="localhost:8000" method=POST path=/api/v1/repositories/foo/branches/trunk/commits request_id=cfc2eec1-b790-43a0-9108-a6ee770cd0a7 sent_bytes=213 service_name=rest_api status_code=201 took=31.923191ms user=me
DEBUG  [2021-01-12T10:10:33+02:00]api/api_controller.go:96 api.(*Dependencies).LogAction performing API action                         action=get_branch_commit_log host="localhost:8000" message_type=action method=GET path="/api/v1/repositories/foo/branches/trunk/commits?amount=-1" request_id=68c2675c-1926-4039-9133-69064f53395e service_name=rest_api user=me
2021/01/12 10:10:33 http: panic serving 127.0.0.1:44520: runtime error: slice bounds out of range [:-1]
goroutine 364 [running]:
net/http.(*conn).serve.func1(0xc0006faa00)
        /snap/go/6745/src/net/http/server.go:1801 +0x147
panic(0x1a2aa40, 0xc00b794d20)
        /snap/go/6745/src/runtime/panic.go:975 +0x47a
github.com/treeverse/lakefs/catalog/rocks.(*cataloger).ListCommits(0xc00052af50, 0x1ee87e0, 0xc0000400e0, 0xc000586b09, 0x3, 0xc000586b16, 0x5, 0x0, 0x0, 0xffffffffffffffff, ...)
        /home/ariels/dev/lakeFS/catalog/rocks/cataloger.go:473 +0x9ae
github.com/treeverse/lakefs/api.(*Controller).CommitsGetBranchCommitLogHandler.func1(0xc000756100, 0x0, 0xc00b78b5c0, 0xc000586b16, 0x5, 0xc000586b09, 0x3, 0xc000755340, 0xc000623901, 0xc00b78b530)
        /home/ariels/dev/lakeFS/api/api_controller.go:476 +0x2e6
github.com/treeverse/lakefs/api/gen/restapi/operations/commits.GetBranchCommitLogHandlerFunc.Handle(0xc009aa1870, 0xc000756100, 0x0, 0xc00b78b5c0, 0xc000586b16, 0x5, 0xc000586b09, 0x3, 0xc000755340, 0x18ba100, ...)
        /home/ariels/dev/lakeFS/api/gen/restapi/operations/commits/get_branch_commit_log.go:25 +0x62
github.com/treeverse/lakefs/api/gen/restapi/operations/commits.(*GetBranchCommitLog).ServeHTTP(0xc009b79360, 0x1ed9560, 0xc000755200, 0xc000756100)
        /home/ariels/dev/lakeFS/api/gen/restapi/operations/commits/get_branch_commit_log.go:73 +0x342
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1ed9560, 0xc000755200, 0xc000756000)
        /home/ariels/go/pkg/mod/github.com/go-openapi/runtime@v0.19.24/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc009b46da0, 0x1ed9560, 0xc000755200, 0xc000756000)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /home/ariels/go/pkg/mod/github.com/go-openapi/runtime@v0.19.24/middleware/router.go:77 +0x359
net/http.HandlerFunc.ServeHTTP(0xc00a16dae0, 0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.SwaggerUI.func1(0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /home/ariels/go/pkg/mod/github.com/go-openapi/runtime@v0.19.24/middleware/swaggerui.go:90 +0x28e
net/http.HandlerFunc.ServeHTTP(0xc00a115d00, 0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /home/ariels/go/pkg/mod/github.com/go-openapi/runtime@v0.19.24/middleware/spec.go:46 +0x190
net/http.HandlerFunc.ServeHTTP(0xc00a115d40, 0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/treeverse/lakefs/api.cookieToAPIHeader.func1(0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /home/ariels/dev/lakeFS/api/handler.go:201 +0x1e6
net/http.HandlerFunc.ServeHTTP(0xc00a174620, 0x1ed9560, 0xc000755200, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/treeverse/lakefs/api.metricsMiddleware.func1(0x7faafc082378, 0xc000623860, 0xc0002cbc00)
        /home/ariels/dev/lakeFS/api/handler.go:215 +0x111
net/http.HandlerFunc.ServeHTTP(0xc00a174640, 0x7faafc082378, 0xc000623860, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1ed95a0, 0xc0007551a0, 0xc0002cbc00)
        /home/ariels/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/promhttp/instrument_server.go:101 +0xda
net/http.HandlerFunc.ServeHTTP(0xc00a172c00, 0x1ed95a0, 0xc0007551a0, 0xc0002cbc00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
github.com/treeverse/lakefs/httputil.DebugLoggingMiddleware.func1(0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /home/ariels/dev/lakeFS/httputil/logging.go:71 +0x6b9
net/http.HandlerFunc.ServeHTTP(0xc00a172c30, 0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00a115f80, 0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /snap/go/6745/src/net/http/server.go:2417 +0x1ad
github.com/treeverse/lakefs/httputil.HostMux.func1(0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /home/ariels/dev/lakeFS/httputil/server.go:80 +0x1b4
net/http.HandlerFunc.ServeHTTP(0xc00aaf0240, 0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /snap/go/6745/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc00a0b75e0, 0x1edad20, 0xc0092d67e0, 0xc0002cba00)
        /snap/go/6745/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0006faa00, 0x1ee87a0, 0xc009171740)
        /snap/go/6745/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /snap/go/6745/src/net/http/server.go:2969 +0x36c

```

**Comment by arielshaqed** [comment]
https://github.com/treeverse/lakeFS/blob/b5b40d2471b3208df30292050078d2a185bbb4d4/cmd/lakectl/cmd/log.go#L73 sets default `--amount` on `logctl log` to -1.  And rocks code does not handle that.
Pagination here might need work, but for now will just make "-1" behave correctly (in the sense of using the default server-side value): we should be able to support old `lakectl` clients until we upgrade the version number on the HTTP endpoint.

**Comment by arielshaqed** [comment]
Treating -1 as the server-side default value is existing behaviour: https://github.com/treeverse/lakeFS/blob/b5b40d2471b3208df30292050078d2a185bbb4d4/catalog/mvcc/cataloger_list_commits.go#L25
