### ISSUE TITLE
BranchLocker test code fail sometimes

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1373]
branch_locker_test fails sometimes with time out: `panic: test timed out after 10m0s`

```
/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:122 +0x246
```

[logs_12078.zip](https://github.com/treeverse/lakeFS/files/5899834/logs_12078.zip)

**Comment by arielshaqed** [comment]
I think I've seen this, too.  E.g. https://github.com/treeverse/lakeFS/pull/1351#issuecomment-770358448 is _precisely_ this test breakage, and went away on a rebase... +rerun.

**Comment by arielshaqed** [comment]
E.g. this failure: https://github.com/treeverse/lakeFS/actions/runs/518485340

**Comment by arielshaqed** [comment]
Here are the *relevant* stacktraces from the above failing test:
```

goroutine 147 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc000043f28)
	/opt/hostedtoolcache/go/1.15.2/x64/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000043f20)
	/opt/hostedtoolcache/go/1.15.2/x64/src/sync/waitgroup.go:130 +0xe5
github.com/jackc/puddle.(*Pool).Close(0xc0001fe880)
	/home/runner/go/pkg/mod/github.com/jackc/puddle@v1.1.3/pool.go:163 +0x31d
github.com/jackc/pgx/v4/pgxpool.(*Pool).Close(...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/pgxpool/pool.go:315
github.com/treeverse/lakefs/testutil.GetDB.func1()
	/home/runner/work/lakeFS/lakeFS/testutil/db.go:143 +0x85
testing.(*common).Cleanup.func1()
	/opt/hostedtoolcache/go/1.15.2/x64/src/testing/testing.go:872 +0x104
testing.(*common).runCleanup(0xc0004dcd80, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/testing/testing.go:949 +0xcb
testing.tRunner.func2(0xc0004dcd80)
	/opt/hostedtoolcache/go/1.15.2/x64/src/testing/testing.go:1121 +0x75
testing.tRunner(0xc0004dcd80, 0x19508d0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/testing/testing.go:1131 +0x22b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.2/x64/src/testing/testing.go:1178 +0x797

goroutine 26 [select, 10 minutes]:
net/http.(*persistConn).roundTrip(0xc0004990e0, 0xc000314340, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:2565 +0x929
net/http.(*Transport).roundTrip(0xc000457e00, 0xc00047ed00, 0x0, 0x8, 0x203000)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:582 +0xe65
net/http.(*Transport).RoundTrip(0xc000457e00, 0xc00047ed00, 0xc000457e00, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/roundtrip.go:17 +0x47
net/http.send(0xc00047ed00, 0x1bdd440, 0xc000457e00, 0x0, 0x0, 0x0, 0x483720, 0x0, 0xc00006e818, 0x483905)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:252 +0x6db
net/http.(*Client).send(0xc000095680, 0xc00047ed00, 0x0, 0x0, 0x0, 0xc000010518, 0x0, 0x1, 0x203000)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:176 +0x1d6
net/http.(*Client).do(0xc000095680, 0xc00047ed00, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:718 +0x2d8
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:586
github.com/ory/dockertest/v3/docker.(*Client).do(0xc0001fa750, 0x18f0e4d, 0x4, 0xc0002628a0, 0x58, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.6.3/docker/client.go:479 +0x827
github.com/ory/dockertest/v3/docker.(*Client).stopContainer(0xc0001fa750, 0xc00011a1c0, 0x40, 0x708, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.6.3/docker/container.go:867 +0x190
github.com/ory/dockertest/v3/docker.(*Client).StopContainer(...)
	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.6.3/docker/container.go:853
github.com/ory/dockertest/v3.(*Resource).Expire.func1(0xc000320c50, 0x708)
	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.6.3/dockertest.go:213 +0x11e
created by github.com/ory/dockertest/v3.(*Resource).Expire
	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.6.3/dockertest.go:212 +0x57

goroutine 281 [chan receive, 9 minutes]:
github.com/treeverse/lakefs/graveler/ref_test.TestBranchLock.func3.1.1(0x22ae9d0, 0x1, 0xc000000034, 0x192745d)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:106 +0x65
github.com/treeverse/lakefs/graveler/ref.(*BranchLocker).Writer.func1(0x1bfea20, 0xc0005f2ba0, 0xc00011e010, 0x18fe745, 0xe, 0x18f9c28)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker.go:37 +0x59f
github.com/treeverse/lakefs/db.(*PgxDatabase).Transact(0xc000321400, 0xc0005f2b60, 0xc00004e100, 0x2, 0x2, 0x4ca17d482671c9bb, 0xc0004b60a8, 0x7f27f2cc07d0, 0x0)
	/home/runner/work/lakeFS/lakeFS/db/database.go:183 +0x343
github.com/treeverse/lakefs/graveler/ref.(*BranchLocker).Writer(0xc000321300, 0x1bfb860, 0xc00011e010, 0x18ef526, 0x1, 0x18f40b8, 0x6, 0xc0005f2b00, 0x19528e0, 0x0, ...)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker.go:27 +0x24c
github.com/treeverse/lakefs/graveler/ref_test.TestBranchLock.func3.1(0xc000321300, 0xc00057f6e0, 0xc00057f740, 0xc0005c4600, 0xc00057f7a0)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:104 +0x15f
created by github.com/treeverse/lakefs/graveler/ref_test.TestBranchLock.func3
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:102 +0x125

goroutine 283 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f27f26a8618, 0x72, 0x1bdef20)
	/opt/hostedtoolcache/go/1.15.2/x64/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00019d198, 0x72, 0xc000022900, 0x1639, 0x1639)
	/opt/hostedtoolcache/go/1.15.2/x64/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.15.2/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00019d180, 0xc0000229c7, 0x1639, 0x1639, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.2/x64/src/internal/poll/fd_unix.go:159 +0x24f
net.(*netFD).Read(0xc00019d180, 0xc0000229c7, 0x1639, 0x1639, 0xc00027f108, 0x4754aa, 0xc000052800)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/fd_posix.go:55 +0x66
net.(*conn).Read(0xc0001222a8, 0xc0000229c7, 0x1639, 0x1639, 0x9, 0xc0008fa000, 0x3d)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/net.go:182 +0xec
io.ReadAtLeast(0x1bdd3a0, 0xc0001222a8, 0xc0000229c7, 0x1639, 0x1639, 0x5, 0x7ffff80000000000, 0x4, 0xc00019d18c)
	/opt/hostedtoolcache/go/1.15.2/x64/src/io/io.go:314 +0x9d
github.com/jackc/chunkreader/v2.(*ChunkReader).appendAtLeast(...)
	/home/runner/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:88
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc000315a40, 0x5, 0xc00027f278, 0x4fac1e, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:78 +0x3f1
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc000493000, 0x3d, 0x0, 0x400, 0x400)
	/home/runner/go/pkg/mod/github.com/jackc/pgproto3/v2@v2.0.6/frontend.go:71 +0x714
github.com/jackc/pgconn.(*PgConn).peekMessage(0xc000538160, 0x0, 0x0, 0x3d, 0x0)
	/home/runner/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:452 +0x30c
github.com/jackc/pgconn.(*ResultReader).readUntilRowDescription(0xc0005381f8)
	/home/runner/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:1491 +0xaa
github.com/jackc/pgconn.(*PgConn).execExtendedSuffix(0xc000538160, 0xc0008fa000, 0x27, 0x400, 0xc0005381f8)
	/home/runner/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:1074 +0x5a6
github.com/jackc/pgconn.(*PgConn).ExecPrepared(0xc000538160, 0x1bfb860, 0xc00011e010, 0xc000043350, 0xa, 0xc0001319e0, 0x1, 0x1, 0xc000042478, 0x1, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:1019 +0x247
github.com/jackc/pgx/v4.(*Conn).execPrepared(0xc00045aa20, 0x1bfb860, 0xc00011e010, 0xc0002a2910, 0xc00004e220, 0x1, 0x1, 0x0, 0x418180, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/conn.go:515 +0x2ae
github.com/jackc/pgx/v4.(*Conn).exec(0xc00045aa20, 0x1bfb860, 0xc00011e010, 0x1917ace, 0x21, 0xc00004e220, 0x1, 0x1, 0x100000010, 0xc0001319a0, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/conn.go:447 +0x48f
github.com/jackc/pgx/v4.(*Conn).Exec(0xc00045aa20, 0x1bfb860, 0xc00011e010, 0x1917ace, 0x21, 0xc00004e220, 0x1, 0x1, 0xc00027fa30, 0x440871, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/conn.go:396 +0xdc
github.com/jackc/pgx/v4.(*dbTx).Exec(0xc0001df980, 0x1bfb860, 0xc00011e010, 0x1917ace, 0x21, 0xc00004e220, 0x1, 0x1, 0xc00027fa70, 0x4e6148, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/tx.go:195 +0xc7
github.com/jackc/pgx/v4/pgxpool.(*Tx).Exec(0xc0005f2c80, 0x1bfb860, 0xc00011e010, 0x1917ace, 0x21, 0xc00004e220, 0x1, 0x1, 0x440871, 0x418180, ...)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/pgxpool/tx.go:54 +0xcc
github.com/treeverse/lakefs/db.(*dbTx).Exec(0xc0005f2ca0, 0x1917ace, 0x21, 0xc00004e220, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
	/home/runner/work/lakeFS/lakeFS/db/tx.go:116 +0x11a
github.com/treeverse/lakefs/graveler/ref.(*BranchLocker).MetadataUpdater.func1(0x1bfea20, 0xc0005f2ca0, 0xc00011e010, 0x18fe745, 0xe, 0x18f9c28)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker.go:57 +0x4b9
github.com/treeverse/lakefs/db.(*PgxDatabase).Transact(0xc000321400, 0xc0005f2c60, 0xc00004e1a0, 0x2, 0x2, 0x4ca17d482671c9bb, 0xc000062800, 0x0, 0x7f27f2cc07d0)
	/home/runner/work/lakeFS/lakeFS/db/database.go:183 +0x343
github.com/treeverse/lakefs/graveler/ref.(*BranchLocker).MetadataUpdater(0xc000321300, 0x1bfb860, 0xc00011e010, 0x18ef526, 0x1, 0x18f40b8, 0x6, 0xc00004e190, 0x166d19a, 0x19528e0, ...)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker.go:46 +0x27e
github.com/treeverse/lakefs/graveler/ref_test.TestBranchLock.func3.2(0xc000321300, 0xc0000432c0, 0xc0005f2c00, 0x2, 0x2, 0xc00004e180, 0x2, 0x2, 0x1)
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:124 +0x129
created by github.com/treeverse/lakefs/graveler/ref_test.TestBranchLock.func3
	/home/runner/work/lakeFS/lakeFS/graveler/ref/branch_locker_test.go:122 +0x246
```

**Comment by nopcoder** [comment]
Didn't managed to reproduce this one also by creating another dummy PR and return this step.
From the stack traces, it looks like we don't have another DB connection to perform a lock and operations in parallel.

**Comment by arielshaqed** [comment]
Of these, goroutines 26, 147  are probably because of the timeout teardown.

**Comment by arielshaqed** [comment]
goroutine 281 is blocked with the write lock on the branch, waiting on `chReleaseWriter` to be released (closed).  goroutine 283 is blocked trying to acquire the read ("metaupdate") lock on the branch, so blocked by 281.
There seem no other goroutines in action.  So... why was `chReleaseWriter` never closed?  The only way appears to be that the test exited on a fatal error!  When that happens, `testing` [does not stop other goroutines](https://golang.org/pkg/testing/#T.FailNow):
> FailNow does not stop those other goroutines [(_created during the test_)].

Now, when the main thread exits, the goroutines are still blocked.  That blocks the test `Cleanup` on the DB... which times out.  Along the way, _we lose the fatal error message_.

**Comment by arielshaqed** [comment]
Yay, now we have [a failure with an error message](https://github.com/treeverse/lakeFS/runs/1804798916?check_suite_focus=true)!
```
--- FAIL: TestBranchLock (0.38s)
    --- FAIL: TestBranchLock/committer_wait_for_writers (0.00s)
        branch_locker_test.go:156: Should not acquire writer while committer is waiting, err=<nil>
FAIL
```
