### ISSUE TITLE
Spark metadata client fails tests

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2483]
Tests are not run as part of CI (not part of `make test` in order to reduce dependencies during dev, but that's no excuse for not testing as part of CI!)

```
[info] ByteBufferIndexedBytesSpec:
[info] ByteBufferIndexedBytes
[info] - returns bytes in buffer through iterator
[info] - slices
[info] - doesn't let slices interfere with one another
[info]   exceptions
[info]   - should throw IndexOutOfBoundsException when applied out of bounds
[info]   - iterators should throw NoSuchElementException after end
[info] CountedIteratorSpec:
[info] CountedIterator
[info] - returns original elements
[info] - counts elements
[info] GolangContainerSpec:
[info] io.treeverse.jpebble.GolangContainerSpec *** ABORTED ***
[info]   java.lang.IllegalArgumentException: Resource with path parser-test/go.sum could not be found on any of these classloaders: [jdk.internal.loader.ClassLoaders$AppClassLoader@55054057, sbt.internal.LayeredClassLoader@36fdb68]
[info]   at org.testcontainers.utility.MountableFile.getClasspathResource(MountableFile.java:147)
[info]   at org.testcontainers.utility.MountableFile.forClasspathResource(MountableFile.java:97)
[info]   at org.testcontainers.utility.MountableFile.forClasspathResource(MountableFile.java:66)
[info]   at org.testcontainers.containers.GenericContainer.withClasspathResourceMapping(GenericContainer.java:1196)
[info]   at org.testcontainers.containers.GenericContainer.withClasspathResourceMapping(GenericContainer.java:1188)
[info]   at com.dimafeng.testcontainers.GenericContainer$$anonfun$$lessinit$greater$3.apply(GenericContainer.scala:41)
[info]   at com.dimafeng.testcontainers.GenericContainer$$anonfun$$lessinit$greater$3.apply(GenericContainer.scala:41)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at com.dimafeng.testcontainers.GenericContainer.<init>(GenericContainer.scala:41)
[info]   at com.dimafeng.testcontainers.GenericContainer$.apply(GenericContainer.scala:80)
[info]   ...
[info] BlockParserSpec:
[info] readMagic
[info] - can read magic exactly
[info] - can read magic with a suffix
[info] - fails to read changed magic
[info] - fails to read truncated magic
[info] readUnsignedVarLong
[info]   handles sample case in doc
[info]   - parses 300
[info]   handles test cases from Golang encoding/binary test code
[info]   - parses -9223372036854775808
[info]   - parses -9223372036854775807
[info]   - parses -1
[info]   - parses 0
[info]   - parses 1
[info]   - parses 2
[info]   - parses 10
[info]   - parses 20
[info]   - parses 63
[info]   - parses 64
[info]   - parses 65
[info]   - parses 127
[info]   - parses 128
[info]   - parses 129
[info]   - parses 255
[info]   - parses 256
[info]   - parses 257
[info]   - parses 9223372036854775807
[info] readSignedVarLong
[info]   handles sample cases in docs
[info]   - parses zero
[info]   - parses -1
[info]   - parses 1
[info]   - parses -2
[info]   - parses 2
[info]   handles test cases from Golang encoding/binary test code
[info]   - parses -9223372036854775808
[info]   - parses -9223372036854775807
[info]   - parses -1
[info]   - parses 0
[info]   - parses 1
[info]   - parses 2
[info]   - parses 10
[info]   - parses 20
[info]   - parses 63
[info]   - parses 64
[info]   - parses 65
[info]   - parses 127
[info]   - parses 128
[info]   - parses 129
[info]   - parses 255
[info]   - parses 256
[info]   - parses 257
[info]   - parses 9223372036854775807
[info] readInt32
[info]   reads little-endian int32s
[info]   - parses -1
[info]   - parses 2147483647
[info]   - parses -2147483648
[info]   - parses 256
[info]   - parses 67305985
[info]   - parses 257
[info]   - parses -1719109786
[info] read RocksDB SSTable
[info] - internal: load h.txt
[info]   h.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.block-bloom.no-compression.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.no-compression.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.no-compression.two_level_index.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.table-bloom.no-compression.prefix_extractor.no_whole_key_filter.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.table-bloom.no-compression.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info]   h.table-bloom.sst
[info]   - reads footer
[info]   - dumps properties
[info]   - reads everything
[info] Run completed in 786 milliseconds.
[info] Total number of tests run: 82
[info] Suites: completed 3, aborted 1
[info] Tests: succeeded 82, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error]         io.treeverse.jpebble.GolangContainerSpec
[error] (lakefs-spark-client-247 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (lakefs-spark-client-301 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 42 s, completed Sep 20, 2021, 10:48:21 AM
```

**Comment by arielshaqed** [comment]
Odd... `git bisect` says a7b223c57c0632b2b769a2383944803e0f496e3e is the first bad commit... but that's the initial test. :confused:
