### ISSUE TITLE
Nessie: test lakeFS S3 with Spark 3.x fails 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2651]
Link to the failing run: https://github.com/treeverse/lakeFS/runs/4124807683?check_suite_focus=true

```
Exception in thread "main" io.lakefs.clients.api.ApiException: Not Found
	at io.lakefs.clients.api.ApiClient.handleResponse(ApiClient.java:1029)
	at io.lakefs.clients.api.ApiClient.execute(ApiClient.java:942)
	at io.lakefs.clients.api.RetentionApi.prepareGarbageCollectionCommitsWithHttpInfo(RetentionApi.java:285)
	at io.lakefs.clients.api.RetentionApi.prepareGarbageCollectionCommits(RetentionApi.java:262)
	at io.treeverse.clients.ApiClient.prepareGarbageCollectionCommits(ApiClient.scala:65)
	at io.treeverse.clients.GarbageCollector$.main(GarbageCollector.scala:269)
	at io.treeverse.clients.GarbageCollector.main(GarbageCollector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/11/06 07:41:39 INFO SparkContext: Invoking stop() from shutdown hook
21/11/06 07:41:39 INFO SparkUI: Stopped Spark web UI at http://339778583dce:4040
21/11/06 07:41:39 INFO StandaloneSchedulerBackend: Shutting down all executors
21/11/06 07:41:39 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
21/11/06 07:41:40 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/11/06 07:41:40 INFO MemoryStore: MemoryStore cleared
21/11/06 07:41:40 INFO BlockManager: BlockManager stopped
21/11/06 07:41:40 INFO BlockManagerMaster: BlockManagerMaster stopped
21/11/06 07:41:40 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/11/06 07:41:40 INFO SparkContext: Successfully stopped SparkContext
21/11/06 07:41:40 INFO ShutdownHookManager: Shutdown hook called
21/11/06 07:41:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-f7f96cbb-2f7f-4981-a6b3-8f906deab06e
21/11/06 07:41:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-1cd18334-4d2b-4891-bb87-efc08d3c8690
1
Expected lakefs://test-data/09d9016a12777fe/commits/commit-four to be removed by garbage collection
Error: Process completed with exit code 1.
```

**Comment by talSofer** [comment]
duplicates #2646
