### ISSUE TITLE
Improve error messages in HadoopFS

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2801]
The Stacktrace returned from failed API operations in the HadoopFS implementation loses some important context (Error message, HTTP status code, error body in the response - and request ID), making it very hard to debug configuration issues without tailing the log(s) of lakeFS server(s) itself.

#### steps to reproduce:

1. Setup a Spark cluster with the [lakeFS Hadoop Filesystem implementation](https://docs.lakefs.io/integrations/spark.html#access-lakefs-using-the-lakefs-specific-hadoop-filesystem)
2. Attempt to read or write from e.g. an invalid lakefs branch:

```scala
val df =  spark.read.parquet("lakefs://repo-that-doesnt-exist/main/path/to/data")
display(df)
```

3. The error message and stack trace will look something like this:

```scala
java.io.IOException: listObjects
at io.lakefs.LakeFSFileSystem$ListingIterator.readNextChunk(LakeFSFileSystem.java:901)
	at io.lakefs.LakeFSFileSystem$ListingIterator.hasNext(LakeFSFileSystem.java:881)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:707)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:40)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1439)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:50)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:392)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:384)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:373)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:373)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:857)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:835)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:1)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:49)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:51)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw.<init>(command-2619134052294416:53)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw.<init>(command-2619134052294416:55)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw.<init>(command-2619134052294416:57)
	at linedbcb5b3933f641889105c8113a5226a333.$read.<init>(command-2619134052294416:59)
	at linedbcb5b3933f641889105c8113a5226a333.$read$.<init>(command-2619134052294416:63)
	at linedbcb5b3933f641889105c8113a5226a333.$read$.<clinit>(command-2619134052294416)
	at linedbcb5b3933f641889105c8113a5226a333.$eval$.$print$lzycompute(<notebook>:7)
	at linedbcb5b3933f641889105c8113a5226a333.$eval$.$print(<notebook>:6)
	at linedbcb5b3933f641889105c8113a5226a333.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:204)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:789)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:742)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:431)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:408)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lakefs.clients.api.ApiException: 
	at io.lakefs.clients.api.ApiClient.handleResponse(ApiClient.java:1029)
	at io.lakefs.clients.api.ApiClient.execute(ApiClient.java:942)
	at io.lakefs.clients.api.ObjectsApi.listObjectsWithHttpInfo(ObjectsApi.java:638)
	at io.lakefs.clients.api.ObjectsApi.listObjects(ObjectsApi.java:611)
	at io.lakefs.LakeFSFileSystem$ListingIterator.readNextChunk(LakeFSFileSystem.java:892)
	at io.lakefs.LakeFSFileSystem$ListingIterator.hasNext(LakeFSFileSystem.java:881)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:707)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:40)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1439)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:50)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:392)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:384)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:373)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:373)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:857)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:835)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:1)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:49)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw$$iw.<init>(command-2619134052294416:51)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw$$iw.<init>(command-2619134052294416:53)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw$$iw.<init>(command-2619134052294416:55)
	at linedbcb5b3933f641889105c8113a5226a333.$read$$iw.<init>(command-2619134052294416:57)
	at linedbcb5b3933f641889105c8113a5226a333.$read.<init>(command-2619134052294416:59)
	at linedbcb5b3933f641889105c8113a5226a333.$read$.<init>(command-2619134052294416:63)
	at linedbcb5b3933f641889105c8113a5226a333.$read$.<clinit>(command-2619134052294416)
	at linedbcb5b3933f641889105c8113a5226a333.$eval$.$print$lzycompute(<notebook>:7)
	at linedbcb5b3933f641889105c8113a5226a333.$eval$.$print(<notebook>:6)
	at linedbcb5b3933f641889105c8113a5226a333.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:204)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:789)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:742)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:431)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:408)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
```

What we're missing here is important information that is received from the lakeFS server (which actually returns a pretty informative error message when trying to list a path in a non-existent repository:

```json
{"message":"repository not found"}
```

As well as an appropriate HTTP status code (404) and an `x-request-id` HTTP header with a unique ID for the request that could be used to correlate between the client's behavior and information in the lakeFS server log.
Ideally, the stacktrace and error message returned above should encode some of this (very useful) information to ease troubleshooting and improve overall system observability.

**Comment by gogi2811** [comment]
@ozkatz  can you add the steps to replicate the error message?
Once clear , I am thinking of taking this up.

**Comment by ozkatz** [comment]
Thanks @gogi2811 - sure, I've edited the issue itself, adding steps to reproduce

**Comment by vaibhavk1992** [comment]
@itaiad200 Please assign this issue to me

**Comment by itaiad200** [comment]
@vaibhavk1992 any update?

**Comment by vaibhavk1992** [comment]
@itaiad200 Moving a bit slowly because of office works. But yes working on it.
