### ISSUE TITLE
BUG: lakectl get panic when the response is the not found html page

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#2935]
1. Edit the lakectl.yaml file and change for example the endpoint_url value to a wrong URI (http://127.0.0.1:8000/api/v2)
2. Run `lakectl repo list` command

You will get:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x105b0f67c]

goroutine 1 [running]:
github.com/treeverse/lakefs/cmd/lakectl/cmd.glob..func65(0x106e1eda0, 0x106e6e4e0, 0x0, 0x0)
	/home/runner/work/lakeFS/lakeFS/cmd/lakectl/cmd/repo.go:34 +0x1bc
github.com/spf13/cobra.(*Command).execute(0x106e1eda0, 0x106e6e4e0, 0x0, 0x0, 0x106e1eda0, 0x106e6e4e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x106e1f7a0, 0x1400018e000, 0x14000072768, 0x104ab227c)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/treeverse/lakefs/cmd/lakectl/cmd.Execute()
	/home/runner/work/lakeFS/lakeFS/cmd/lakectl/cmd/root.go:133 +0x60
main.main()
	/home/runner/work/lakeFS/lakeFS/cmd/lakectl/main.go:6 +0x20
```

This is because we don't catch any exception here (since the response status is in this case is 200) but we are trying to get the status' json which doesn't exist (we returned the not found html page).

**Comment by idanovo** [comment]
The suggested solution by @ari-hacks  is to check in the request header if the request was sent by a browser and send the "not-found" HTML page only if this is the case.
