### ISSUE TITLE
question : spark-submit garbagecollector arguments not picked up

### ISSUE THREAD

**Issue by hugoJuhel** [treeverse/lakeFS#2940]
# Issue 
GC jobs triggered through `spark-submit` does not pick-up the arguments `repo-name` and `region-name`.

Following the [documentation ](https://docs.lakefs.io/v0.52/reference/garbage-collection.html#running-the-gc-job) I tried to trigger a GC job using on a repo named `core-models`. 

The following command fails with stack trace : 
```bash
spark-submit --class io.treeverse.clients.GarbageCollector \
  -c spark.hadoop.lakefs.api.url=http://lakefs.<secret>/api/v1  \
  -c spark.hadoop.lakefs.api.access_key=<secret> \
  -c spark.hadoop.lakefs.api.secret_key=<secret> \
  -c spark.hadoop.fs.s3a.access.key=<secret> \
  -c spark.hadoop.fs.s3a.secret.key=<secret>\
  -c spark.hadoop.fs.s3a.endpoint=<custom-endpoint>\
  --packages io.lakefs:lakefs-spark-client-301_2.12:0.5.0 \
  core-models us-east-1
```

```bash
22/02/10 12:30:44 ERROR SparkContext: Failed to add file:<spark-home>/spark-3.2.1-bin-hadoop3.2/sbin/core-models2 to Spark environment
java.io.FileNotFoundException: Jar <spark-home>/spark-3.2.1-bin-hadoop3.2/sbin/core-models2 not found
        at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1935)
        at org.apache.spark.SparkContext.addJar(SparkContext.scala:1990)
        at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:503)
        at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:503)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:503)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
        at io.treeverse.clients.GarbageCollector$.main(GarbageCollector.scala:252)
        at io.treeverse.clients.GarbageCollector.main(GarbageCollector.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

# Version
Version
- spark : 3.2.1
- lakefs : 0.52.2

Is there any way to trigger the GC class ?

**Comment by johnnyaug** [comment]
@hugoJuhel, welcome and thank you for opening this issue!

Unfortunately this version of the documentation had errors in it. 
Please use the command from the [up-to-date documentation](https://docs.lakefs.io/reference/garbage-collection.html) and let us know if it works:
```
spark-submit --class io.treeverse.clients.GarbageCollector \
  -c spark.hadoop.lakefs.api.url=https://lakefs.example.com:8000/api/v1  \
  -c spark.hadoop.lakefs.api.access_key=BOO \
  -c spark.hadoop.lakefs.api.secret_key=BOO \
  -c spark.hadoop.fs.s3a.access.key=BOO \
  -c spark.hadoop.fs.s3a.secret.key=BOO \
  --packages io.lakefs:lakefs-spark-client-301_2.12:0.1.6 \
  example-repo us-east-1
```

**Comment by hugoJuhel** [comment]
Hi @johnnyaug ,

Thanks for your answer!

I have tried the command you gave me (with a custom `spark.hadoop.fs.s3a.endpoint`), but still, I got the issue about the missing JAR (`core-models` being the name of my repo on lakefs).

I'm really sorry, I'm obviously doing something wrong but can't figure it out.

```bash
spark-submit --class io.treeverse.clients.GarbageCollector \
  -c spark.hadoop.lakefs.api.url=http://<secret>/api/v1  \
  -c spark.hadoop.lakefs.api.access_key=<secret> \
  -c spark.hadoop.lakefs.api.secret_key=<secret> \
  -c spark.hadoop.fs.s3a.access.key=juhelh \
  -c spark.hadoop.fs.s3a.secret.key=<secret> \
  -c spark.hadoop.fs.s3a.endpoint=http://<secret> \
  --packages io.lakefs:lakefs-spark-client-301_2.12:0.1.6 \
  core-models us-east-1
```

```bash
22/02/14 12:22:57 ERROR SparkContext: Failed to add file:/home/juhelh/core-models to Spark environment
java.io.FileNotFoundException: Jar /home/juhelh/core-models not found
        at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1935)
        at org.apache.spark.SparkContext.addJar(SparkContext.scala:1990)
        at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:503)
        at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:503)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:503)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
        at io.treeverse.clients.GarbageCollector$.main(GarbageCollector.scala:252)
        at io.treeverse.clients.GarbageCollector.main(GarbageCollector.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by Jonathan-Rosenberg** [comment]
Hi @hugoJuhel,
There seems to be an additional mistake in the documentation. Sorry about that...
The following command should work as it's specifying lakeFS's spark client application jar as the entry point for the spark job.
You'll first have to download the uber-jar from [here](http://treeverse-clients-us-east.s3-website-us-east-1.amazonaws.com/lakefs-spark-client-301/0.1.6/lakefs-spark-client-301-assembly-0.1.6.jar), then specify it's path when running the job (instead of `<APPLICATION-JAR-PATH>`):
```
spark-submit --class io.treeverse.clients.GarbageCollector \
  -c spark.hadoop.lakefs.api.url=http://<secret>/api/v1  \
  -c spark.hadoop.lakefs.api.access_key=<secret> \
  -c spark.hadoop.lakefs.api.secret_key=<secret> \
  -c spark.hadoop.fs.s3a.access.key=juhelh \
  -c spark.hadoop.fs.s3a.secret.key=<secret> \
  -c spark.hadoop.fs.s3a.endpoint=http://<secret> \
  <APPLICATION-JAR-PATH> \
  core-models us-east-1
```
(the `--packages` config is redundant when using the uber-jar)

**Comment by itaiad200** [comment]
@Jonathan-Rosenberg Should we close this?
