### ISSUE TITLE
"lakectl ingest" does not work on demo [was: Basic Spark Example]

### ISSUE THREAD

**Issue by phzietsman** [treeverse/lakeFS#2945]
Hey there,

I've been trying to get a basic Spark example going for client demo. I'm running it on zepl.com here is the sample:

I got my sample data this way:

```
export AWS_REGION=us-west-2

lakectl repo create lakefs://source-data s3://treeverse-demo-lakefs-storage-production/user_m1eo6o342cajzqaa/source-data

lakectl repo create lakefs://processed-data s3://treeverse-demo-lakefs-storage-production/user_m1eo6o342cajzqaa/processed-data

# https://registry.opendata.aws/speedtest-global-performance/
lakectl ingest \
  --from s3://ookla-open-data/parquet/performance/type=mobile/ \
  --to lakefs://source-data/main/performance/type=mobile/

lakectl commit lakefs://source-data/main -m 'source data loaded'
```

```scala
spark.sparkContext.hadoopConfiguration.set("fs.s3a.access.key", "xxx")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.secret.key", "xxx")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.endpoint", "https://xxx.lakefs-demo.io")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.path.style.access", "true")

val df = spark.read.parquet("s3a://source-data/main/performance/type=mobile/year=2019/quarter=1/2019-01-01_performance_mobile_tiles.parquet")

df.printSchema()
```

When I try to read the data directly from the Ookla bucket the code works just fine.

When I try to download the parquet files from LakeFS, the download fails.

![image](https://user-images.githubusercontent.com/11902058/153770046-2895cfa6-4312-4d17-9a12-8fa91c86f4a7.png)

This is the error I'm getting
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, notebook-38b45b2c37ed481bb32808972b5d0cdc-execute, executor driver): org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:376)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:444)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:490)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:484)
	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:75)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hadoop.fs.s3a.AWSS3IOException: Reopen at position 0 on s3a://source-data/main/performance/type=mobile/year=2019/quarter=1/2019-01-01_performance_mobile_tiles.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098), S3 Extended Request ID: 6E94828E6D361098: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:194)
	at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:178)
	at org.apache.hadoop.fs.s3a.S3AInputStream.onReadFailure(S3AInputStream.java:367)
	at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:340)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.parquet.io.DelegatingSeekableInputStream.read(DelegatingSeekableInputStream.java:61)
	at org.apache.parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:80)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:520)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:505)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:499)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:476)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:451)
	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:373)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098), S3 Extended Request ID: 6E94828E6D361098
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4229)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4176)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1380)
	at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:171)
	... 24 more

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
  at scala.Option.foreach(Option.scala:407)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2135)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2154)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2179)
  at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
  at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
  at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:69)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:494)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:107)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:163)
  at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
  at scala.Option.orElse(Option.scala:447)
  at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:418)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
  at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:758)
  at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:736)
  ... 44 elided
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
  at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
  at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:376)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:444)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:490)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:484)
  at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:75)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:127)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
  ... 3 more
Caused by: org.apache.hadoop.fs.s3a.AWSS3IOException: Reopen at position 0 on s3a://source-data/main/performance/type=mobile/year=2019/quarter=1/2019-01-01_performance_mobile_tiles.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098), S3 Extended Request ID: 6E94828E6D361098: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098)
  at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:194)
  at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:178)
  at org.apache.hadoop.fs.s3a.S3AInputStream.onReadFailure(S3AInputStream.java:367)
  at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:340)
  at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
  at org.apache.parquet.io.DelegatingSeekableInputStream.read(DelegatingSeekableInputStream.java:61)
  at org.apache.parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:80)
  at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:520)
  at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:505)
  at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:499)
  at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:476)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:451)
  at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:373)
  at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
  at scala.util.Success.$anonfun$map$1(Try.scala:255)
  at scala.util.Success.map(Try.scala:213)
  at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
  at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
  at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e3577106-0241-4e7b-bbbe-6482048b90df; S3 Extended Request ID: 6E94828E6D361098)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4229)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4176)
  at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1380)
  at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:171)
  ... 24 more
```

Can someone please help with this.

**Comment by arielshaqed** [comment]
You have no access to your hosted lakeFS logs on the demo, so this issue was impossible for you to debug.  I am sorry about that.

Demo environments are (understandably, I hope) intentionally limited.  And it turns out that we do not currently allow demo environments to access other S3 buckets.  And as you show, import will not work without allowing this.  I have kicked off an internal discussion at Treeverse to see if we can allow this.

If it's OK with you, I would like to leave this issue open until I have a definitive answer one way or the other.  (We are having the discussion regardless of the state of this bug, of course.)

**Comment by arielshaqed** [comment]
> Thanks for the feedback! And I 100% understand the reason for the limitation.

You'll be happy to hear it now seems to be working on a staging environment.  I'll see when we can release it to the production demo environment :-)

**Comment by arielshaqed** [comment]
Hi @phzietsman !

Happy to report we did some permissions work, and this now works for me.  Closing; it would be great if you could verify that it now works for you.

if you need more time on your demo installation, please contact me (@Ariel Shaqed (Scolnicov) on the public Slack (https://lakefs.io/slack).  THANKS!
