### ISSUE TITLE
"Everything Bagel" Jupyter notebook container does not support S3A

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2947]
## What I did

1. Start `docker-compose`
1. Access http://localhost:8888 with the baked-in password ("`lakefs`")
1. Try to run this cell:
   ```py
   import pyspark
   from pyspark.sql import SparkSession

   conf = pyspark.SparkConf()
   conf.set("fs.s3a.access.key", "AKIAIOSFODNN7EXAMPLE")
   conf.set("fs.s3a.secret.key", "mykey")
   conf.set("fs.s3a.endpoint", "http://lakefs:8000")
   conf.set("fs.s3a.path.style.access", "true")
   sc = SparkSession.builder.config(conf=conf).getOrCreate()
   df = sc.sql("select 'spark' as hello ") #this statement works
   path = "s3a://testrepo/main/Sample-Spreadsheet-10-rows.csv"
   df2 = sc.read.csv(path) #this is throwing the error message. Below is the complete error log
```

## Result

Verbose error message, followed by:

``` text
Py4JJavaError: An error occurred while calling o42.csv.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
```

## Expected result

A file-not-found message from S3A filesystem.

# What have I tried

I tried to locate a hadoop-aws JAR on the container, but found none.  Given
that I am not a PySpark expert, I am at a loss what to do next.

**Comment by arielshaqed** [comment]
Source: https://lakefs.slack.com/archives/C016726JLJW/p1644833623767149

**Comment by Jonathan-Rosenberg** [comment]
Indeed the related jars weren't found in the jupyter notebook container.
The jars are not included in the image we use by default.
### Solution
Create a Dockerfile based on the currently used jupyter notebook Docker image and add the required jars.

**Comment by arielshaqed** [comment]
I'm going to have to reopen this: following a contributor on Slack, I pulled, rebuilt and ran. Still get the same error.
Perhaps you ran with some added classpath directory that failed to make it into the PR?

**Comment by arielshaqed** [comment]
This seems to work for me:
```py
import pyspark
from pyspark.sql import SparkSession

conf = pyspark.SparkConf()
conf.set("spark.hadoop.fs.s3a.access.key", "AKIAIOSFODNN7EXAMPLE")
conf.set("spark.hadoop.fs.s3a.secret.key", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY")
conf.set("spark.hadoop.fs.s3a.endpoint", "http://lakefs:8000")
conf.set("spark.hadoop.fs.s3a.path.style.access", "true")
sc = SparkSession.builder.config(conf=conf).getOrCreate()
df = sc.sql("select 'spark' as hello ") #this statement works
path = "s3a://example/main/path.csv"
df2 = sc.read.csv(path) #this is throwing the error message. Below is the complete error log
```
