### ISSUE TITLE
"make lint" fails

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3390]
This is probably because of golangci/golangci-lint#2859.

To reproduce, `make build lint` :-(

```
[33mWARN[0m [linters context] Panic: nilness: package "ntlmssp" (isInitialPkg: false, needAnalyzeSource: true): runtime error: index out of range [1] with length 1: goroutine 16290 [running]:
runtime/debug.Stack()
	/home/ariels/sdk/go1.17.6/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:508 +0x155
panic({0x1116440, 0xc001c484f8})
	/home/ariels/sdk/go1.17.6/src/runtime/panic.go:1038 +0x215
honnef.co/go/tools/analysis/facts/nilness.impl.func2({0x13630a8, 0xc00635c480})
	/home/ariels/go/pkg/mod/honnef.co/go/tools@v0.1.2/analysis/facts/nilness/nilness.go:161 +0xddb
honnef.co/go/tools/analysis/facts/nilness.impl.func2({0x1363790, 0xc003eddce0})
	/home/ariels/go/pkg/mod/honnef.co/go/tools@v0.1.2/analysis/facts/nilness/nilness.go:148 +0xe7f
honnef.co/go/tools/analysis/facts/nilness.impl(0xc006d7c0d0, 0xc0028b30e0, 0xc002dc1ca8)
	/home/ariels/go/pkg/mod/honnef.co/go/tools@v0.1.2/analysis/facts/nilness/nilness.go:239 +0x48b
honnef.co/go/tools/analysis/facts/nilness.run(0xc006d7c0d0)
	/home/ariels/go/pkg/mod/honnef.co/go/tools@v0.1.2/analysis/facts/nilness/nilness.go:66 +0x126
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc005fa4f80)
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:590 +0x9fe
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:512 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00068b630, {0x11663e8, 0x7}, 0xc002a96f60)
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc005fa4f80)
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:511 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x7465622065726120)
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:1059 +0x67
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/home/ariels/go/pkg/mod/github.com/golangci/golangci-lint@v1.38.0/pkg/golinters/goanalysis/runner.go:1054 +0x1fd 
[33mWARN[0m [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: nilness: package "ntlmssp" (isInitialPkg: false, needAnalyzeSource: true): runtime error: index out of range [1] with length 1 
[31mERRO[0m Running error: goanalysis_metalinter: nilness: package "ntlmssp" (isInitialPkg: false, needAnalyzeSource: true): runtime error: index out of range [1] with length 1 
```

**Comment by arielshaqed** [comment]
@itaiad200 FYI
