### ISSUE TITLE
GC+: DataLister: Relative path in absolute URI: gc-migrate-lakefs-0-40-1:b40b9540-91f0-4add-96ba-205f17e03c57

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4766]
When iterating over slices with the format `x:y` (this can happen on old link physical addresses syntax), we get an exception since HDFS assumes a schema and therefore treats the string as an absolute path

Link to known issue:
https://issues.apache.org/jira/browse/HDFS-14762

Trace:
```
	at io.treeverse.gc.UncommittedGarbageCollector.main(UncommittedGarbageCollector.scala)
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: gc-migrate-lakefs-0-40-1:b40b9540-91f0-4add-96ba-205f17e03c57
	at org.apache.hadoop.fs.Path.initialize(Path.java:263)
	at org.apache.hadoop.fs.Path.<init>(Path.java:221)
	at org.apache.hadoop.fs.Path.<init>(Path.java:119)
	at io.treeverse.gc.ParallelDataLister.$anonfun$listData$1(DataLister.scala:55)
```

**Comment by N-o-Z** [comment]
@johnnyaug  would love to get your input here - do you have any idea how to WA this and list files on a path which holds ':'?
