### ISSUE TITLE
 Rclone export Docker container fails to run

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4841]
Reported by @iddoavn.

[...]

I tried using docker and run (I’m on an M1 chip, hence the --platform):

```shell
docker run --platform linux/amd64 \
	-e LAKEFS_ACCESS_KEY=XXX -e LAKEFS_SECRET_KEY=XXX \
	-e LAKEFS_ENDPOINT=https://aws-demo.lakefs.io/api/v1 \
	-e S3_ACCESS_KEY=XXX -e S3_SECRET_KEY=XXX \
	-it treeverse/lakefs-rclone-export:latest understand-lakefs-repo \
	s3://axolotl-company/production/latest --branch="production"

```

Output:

``` 
Traceback (most recent call last):
  File "lakefs_export.py", line 119, in <module>
    main()
  File "lakefs_export.py", line 90, in main
    raise Exception("Error while executing rclone command: ", process.stderr)
Exception: ('Error while executing rclone command: ', b'2022/12/19 21:16:42 NOTICE: S3 bucket axolotl-company path production: Switched region to "us-east-2" from "us-east-1"\n2022/12/19 21:16:42 ERROR : S3 bucket understand-lakefs-repo path production: error reading source root directory: directory not found\n2022/12/19 21:16:42 ERROR : Attempt 1/3 failed with 1 errors and: directory not found\n2022/12/19 21:16:42 ERROR : S3 bucket understand-lakefs-repo path production: error reading source root directory: directory not found\n2022/12/19 21:16:42 ERROR : Attempt 2/3 failed with 1 errors and: directory not found\n2022/12/19 21:16:42 ERROR : S3 bucket understand-lakefs-repo path production: error reading source root directory: directory not found\n2022/12/19 21:16:42 ERROR : Attempt 3/3 failed with 1 errors and: directory not found\n2022/12/19 21:16:42 Failed to copy: directory not found\n')
```

**Comment by arielshaqed** [comment]
@nopcoder says:
> the lakefs endpoint is not API endpoint - at least for the first command use https://aws-demo.lakefs.io/

Assigning back to @iddoavn , but please assign it back to me with comment if it still fails!

**Comment by iddoavn** [comment]
Continuing to investigate today, running:
`iddoavneri@Iddos-MacBook-Pro ~ % docker run --platform linux/amd64 -e LAKEFS_ACCESS_KEY=XXX -e LAKEFS_SECRET_KEY=XXX-e LAKEFS_ENDPOINT=https://aws-demo.lakefs.io -e S3_ACCESS_KEY=XXX -e S3_SECRET_KEY=XXX -it treeverse/lakefs-rclone-export:latest understand-lakefs-repo s3://axolotl-company/production/latest --branch=production`

Does actually produce the files in the  `s3://axolotl-company/production/latest` bucket. 
I am still getting this error though:

```
Traceback (most recent call last):
  File "lakefs_export.py", line 119, in <module>
    main()
  File "lakefs_export.py", line 90, in main
    raise Exception("Error while executing rclone command: ", process.stderr)
Exception: ('Error while executing rclone command: ', b'2022/12/20 17:26:51 NOTICE: S3 bucket axolotl-company path production: Switched region to "us-east-2" from "us-east-1"\n')

```

**Comment by arielshaqed** [comment]
I am getting a _different_ error message:
```
Traceback (most recent call last):
  File "lakefs_export.py", line 119, in <module>
    main()
  File "lakefs_export.py", line 90, in main
    raise Exception("Error while executing rclone command: ", process.stderr)
Exception: ('Error while executing rclone command: ', b'2022/12/28 20:10:42 ERROR : README.md: Failed to copy: s3 upload: 400 Bad Request:
```
Followed by an XML error message for each file, which I placed in its own block to get syntax highlighting:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BadDigest
    </Code>
    <Message>The Content-MD5 you specified did not match what we received.
    </Message>
    <ExpectedDigest>6965c70f22899a82baabc43c952561f0
    </ExpectedDigest>
    <CalculatedDigest>dwv+Q3G0x6k6Vzk/oIa7Qw==
    </CalculatedDigest>
    <RequestId>04M123DDE50HASXC
    </RequestId>
    <HostId>kp/bXirs85c2F5ZjbdZttI2hf+8D0+kvMkwvZ8Xky4lGjj5KROt8ouA7lcRXHvJD2qE3365XszjZXDpYte05RQ==
    </HostId>
</Error>

<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BadDigest
    </Code>
    <Message>The Content-MD5 you specified did not match what we received.
    </Message>
    <ExpectedDigest>6965c70f22899a82baabc43c952561f0
    </ExpectedDigest>
    <CalculatedDigest>dwv+Q3G0x6k6Vzk/oIa7Qw==
    </CalculatedDigest>
    <RequestId>04M123DDE50HASXC
    </RequestId>
    <HostId>kp/bXirs85c2F5ZjbdZttI2hf+8D0+kvMkwvZ8Xky4lGjj5KROt8ouA7lcRXHvJD2qE3365XszjZXDpYte05RQ==
    </HostId>
</Error>
```

First order of business: improve error messages :-)  The script hides Rclone error message and makes them _much_ less readable.

**Comment by arielshaqed** [comment]
In more detail: the copy seems _good_, but digest comparison fails.

@iddoavn - do you also get such errors?  Or only "yours"?
