### ISSUE TITLE
Fail to run Spark export

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4842]
@iddoavn writes:

I tried going down the spark-submit route instead.

Run:

```sh
spark-submit --conf spark.hadoop.lakefs.api.url=https://aws-demo.lakefs.io/api/v1 \
  --conf spark.hadoop.lakefs.api.access_key=XXX \
  --conf spark.hadoop.lakefs.api.secret_key=XXX \
  --packages io.lakefs:lakefs-spark-client-301_2.12:0.6.0 \
  --class io.treeverse.clients.Main export-app understand-lakefs-repo s3://axolotl-company/production/latest \
  --branch=production
```

And getting:
```
: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] javax.jms#jms;1.1!jms.jar (268ms)	==== central: tried	  https://repo1.maven.org/maven2/javax/jms/jms/1.1/jms-1.1.jar		[NOT FOUND  ] com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar (19ms)	==== central: tried	  https://repo1.maven.org/maven2/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar		[NOT FOUND  ] com.sun.jmx#jmxri;1.2.1!jmxri.jar (28ms)	==== central: tried	  https://repo1.maven.org/maven2/com/sun/jmx/jmxri/1.2.1/jmxri-1.2.1.jar		::::::::::::::::::::::::::::::::::::::::::::::		::              FAILED DOWNLOADS            ::		:: ^ see resolution messages for details  ^ ::		::::::::::::::::::::::::::::::::::::::::::::::		:: javax.jms#jms;1.1!jms.jar		:: com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar		:: com.sun.jmx#jmxri;1.2.1!jmxri.jar		:::::::::::::::::::::::::::::::::::::::::::::::: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: javax.jms#jms;1.1!jms.jar, download failed: com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar, download failed: com.sun.jmx#jmxri;1.2.1!jmxri.jar]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at [org.apache.spark.deploy.SparkSubmit.org](http://org.apache.spark.deploy.sparksubmit.org/)$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Which is the same error I get when I run:
```sh
spark-shell --packages io.lakefs:lakefs-spark-client-301_2.12:0.6.0
```

**Comment by talSofer** [comment]
Cannot reproduce the bug, please re-open if it occurs again.
