### ISSUE TITLE
[lakeFSFS, GC, Spark] Wrap API client to report common misconfigurations more clearly

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#5213]
The generated API client generates many exceptions that are _technically correct_ but nearly impossible for users to parse.  Wrap the generated Java API client to detect some of these and wrap them with exceptions that give a better explanation of what went wrong.

The most common breakage is when receiving a non-JSON response.  The API client merely raises an ApiException about the content type.  It **drops** the actual status code and response message.  We see many user reports who are at a loss when receiving a message

```
io.lakefs.hadoop.shade.api.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.lakefs...
```

Worse, this actually occurs somewhere in the middle of several hundred lines of stack trace -- the next comment will have an example.

This cannot be solved on the server: One common occurrence is an incorrect API endpoint.  The failure might not be generated by the actual lakeFS server, it might be by any gateway or reverse proxy on path.  More than that, a poor error report on the client is a client-side bug.

**Comment by arielshaqed** [comment]
Example stacktrace (this one is short, if it fails inside a worker it gets even more horrible!):

```
23/02/06 12:13:28 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: lakefs://repo/main//path/to/my.csv.
java.io.IOException: statObject
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:779)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:46)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:571)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.lakefs.hadoop.shade.api.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.lakefs.hadoop.shade.api.model.ObjectStats
	at io.lakefs.hadoop.shade.api.ApiClient.deserialize(ApiClient.java:822)
	at io.lakefs.hadoop.shade.api.ApiClient.handleResponse(ApiClient.java:1020)
	at io.lakefs.hadoop.shade.api.ApiClient.execute(ApiClient.java:944)
	at io.lakefs.hadoop.shade.api.ObjectsApi.statObjectWithHttpInfo(ObjectsApi.java:1478)
	at io.lakefs.hadoop.shade.api.ObjectsApi.statObject(ObjectsApi.java:1451)
	at io.lakefs.LakeFSFileSystem.getFileStatus(LakeFSFileSystem.java:775)
```

**Comment by arielshaqed** [comment]
Related: #3054, that one shows about a different type of error.  Ideally the same solution would work for both.

**Comment by arielshaqed** [comment]
Related to #2801, which could/might help here too.
