### ISSUE TITLE
[lakeFSFS] First steps in supporting Unity

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#5829]
Support DataBricks Unity Catalog tables in lakeFS.

DoD: One table defined on lakeFS that can be defined and read from DB Unity.

**Comment by arielshaqed** [comment]
## First challenge: Authentication and authorization

### Cannot use the S3 gateway!

Unity uses _IAM roles_ to authenticate.  This will not work with the S3 gateway for _multiple_ reasons, each of which is enough to block this.    Unity is configured with an AWS IAM role, which assumes the AWS customer role.  This won't work with the S3 gateway because:
* There is no shared identity provider between Unity and lakeFS.  So Unity cannot prove to lakeFS that it managed to assume the desired customer role.
* Even suppose we added STS assume-role support to lakeFS (this is #3919).  Without changes on the DB side, Unity would have no way of proving to lakeFS that it is Unity, so lakeFS would have no way of authorizing Unity to assume some lakeFS-side role.

**Comment by arielshaqed** [comment]
## lakeFSFS doesn't work

Attempting to read fails to initialize the underlying filesystem, see [attached stacktrace](https://github.com/treeverse/lakeFS/files/11421290/stack.log).  The important lines appear to be:
```java
Caused by: shaded.databricks.org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on lakefs-sample-us-east-1-staging: com.amazonaws.AmazonClientException: No AWS Credentials provided by AwsCredentialContextTokenProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [com.databricks.backend.daemon.driver.aws.AwsLocalCredentialContextTokenProvider@1da3ba5a: No role specified and no roles available., com.databricks.backend.daemon.driver.aws.ProxiedIAMCredentialProvider@75b4975c: User does not have any IAM roles]: No AWS Credentials provided by AwsCredentialContextTokenProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [com.databricks.backend.daemon.driver.aws.AwsLocalCredentialContextTokenProvider@1da3ba5a: No role specified and no roles available., com.databricks.backend.daemon.driver.aws.ProxiedIAMCredentialProvider@75b4975c: User does not have any IAM roles]
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:207)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:120)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:274)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:333)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:270)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:245)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:679)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:519)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at io.lakefs.storage.SimpleStorageAccessStrategy.createDataInputStream(SimpleStorageAccessStrategy.java:82)
	at io.lakefs.LakeFSFileSystem.open(LakeFSFileSystem.java:198)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
```

#4923 is probably this problem but for writing, or hopefully similar; different messages appeared in the stacktrace.

**Comment by ozkatz** [comment]
@arielshaqed can you share the steps to reproduce this error? the more the detailed the better.
Additionally, if we do require Unity to add support for something in order for this integration to work, we'd need a detailed explanation of what that something is... (once we have an idea, of course)

**Comment by itaiad200** [comment]
Continued elsewhere.
