### ISSUE TITLE
[Bug]: Getting "java.io.IOException: link lakeFS path to physical address" error when I use lakeFSFS to create a Delta table via Azure Databricks notebook

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6099]
### What happened?

Current Behavior:
Getting `java.io.IOException: link lakeFS path to physical address` error when I use lakeFSFS to create a Delta table via Azure Databricks notebook (stack trace below). I am using blob for storage namespace.

my lakeFS Config:
`sudo docker run -d --restart always --pull always -p 8000:8000 -e LAKEFS_STATS_ENABLED=0 -e LAKEFS_BLOCKSTORE_TYPE='azure' -e LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCOUNT='demo' -e LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCESS_KEY='aaa'  -e LAKEFS_BLOCKSTORE_AZURE_DISABLE_PRE_SIGNED_UI=1 --name azureuser_lakefs_1 treeverse/lakefs run --local-settings`

Databricks Cluster Spark config:
```spark.hadoop.fs.lakefs.access.mode presigned
spark.hadoop.fs.lakefs.secret.key aaa
spark.hadoop.fs.lakefs.access.key bbb
spark.hadoop.fs.lakefs.endpoint http://111.222.333.4:8000/api/v1
spark.hadoop.fs.lakefs.impl io.lakefs.LakeFSFileSystem
spark.databricks.delta.preview.enabled true
spark.databricks.delta.logStore.crossCloud.fatal false
```
Using latest io.lakefs:hadoop-lakefs-assembly:0.1.15 library for Databricks cluster.

My code:
`customersTablePath = f"lakefs://{repo}/{mainBranch}/{customersTable}"
df = spark.read.csv('/FileStore/tables/data/OrionStar/CUSTOMER.csv',header=True,schema=customersSchema)
df.write.format("delta").mode("overwrite").save(customersTablePath)`

```
Py4JJavaError                             Traceback (most recent call last)
File <command-3578552658771089>:3
      1 customersTablePath = f"lakefs://{repo}/{mainBranch}/{customersTable}"
      2 df = spark.read.csv('/FileStore/tables/data/OrionStar/CUSTOMER.csv',header=True,schema=customersSchema)
----> 3 df.write.format("delta").mode("overwrite").save(customersTablePath)
      4 df.show(10)

File /databricks/spark/python/pyspark/instrumentation_utils.py:48, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     46 start = time.perf_counter()
     47 try:
---> 48     res = func(*args, **kwargs)
     49     logger.log_success(
     50         module_name, class_name, function_name, time.perf_counter() - start, signature
     51     )
     52     return res

File /databricks/spark/python/pyspark/sql/readwriter.py:1397, in DataFrameWriter.save(self, path, format, mode, partitionBy, **options)
   1395     self._jwrite.save()
   1396 else:
-> 1397     self._jwrite.save(path)

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /databricks/spark/python/pyspark/errors/exceptions.py:228, in capture_sql_exception.<locals>.deco(*a, **kw)
    226 def deco(*a: Any, **kw: Any) -> Any:
    227     try:
--> 228         return f(*a, **kw)
    229     except Py4JJavaError as e:
    230         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o994.save.
: java.io.IOException: link lakeFS path to physical address
	at io.lakefs.LakeFSLinker.link(LakeFSLinker.java:33)
	at io.lakefs.storage.LakeFSFileSystemOutputStream.close(LakeFSFileSystemOutputStream.java:48)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at io.lakefs.LakeFSFileSystem.createDirectoryMarker(LakeFSFileSystem.java:752)
	at io.lakefs.LakeFSFileSystem.mkdirs(LakeFSFileSystem.java:743)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2388)
	at com.databricks.sql.transaction.tahoe.DeltaLog.createLogDirectory(DeltaLog.scala:509)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.write(WriteIntoDelta.scala:277)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2(WriteIntoDelta.scala:104)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2$adapted(WriteIntoDelta.scala:99)
	at com.databricks.sql.transaction.tahoe.DeltaLog.withNewTransaction(DeltaLog.scala:291)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:99)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:1971)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.run(WriteIntoDelta.scala:98)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:201)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.$anonfun$sideEffectResult$1(commands.scala:82)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:79)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:91)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$3(QueryExecution.scala:238)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:165)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:227)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:410)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:172)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1038)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:122)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:360)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:237)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:220)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:233)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:226)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:106)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:316)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:312)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:495)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:226)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:372)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:226)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:180)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:287)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:964)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:429)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:338)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.lakefs.hadoop.shade.api.ApiException: Bad Request
	at io.lakefs.hadoop.shade.api.ApiClient.handleResponse(ApiClient.java:1031)
	at io.lakefs.hadoop.shade.api.ApiClient.execute(ApiClient.java:944)
	at io.lakefs.hadoop.shade.api.StagingApi.linkPhysicalAddressWithHttpInfo(StagingApi.java:348)
	at io.lakefs.hadoop.shade.api.StagingApi.linkPhysicalAddress(StagingApi.java:321)
	at io.lakefs.LakeFSLinker.link(LakeFSLinker.java:30)
	... 65 more
```

Steps to Reproduce:
1. Please contact me. I have Azure Databricks notebook to reproduce this.
2.
3.

### Expected Behavior

Expected Behavior:
How you expected thing to work.

### lakeFS Version

0.102.2

### Deplyoment

Docker

### Affected Clients

hadoop-lakefs-assembly:0.1.15

### Contact Details

amit.kesarwani@treeverse.io

**Comment by Jonathan-Rosenberg** [comment]
lakeFS was misconfigured.

**Comment by ozkatz** [comment]
@Jonathan-Rosenberg can you share more details? what was misconfigured?

**Comment by Jonathan-Rosenberg** [comment]
Sure:
The `LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCOUNT` env var was configured with the resource group that the storage account was a part of instead of the storage account itself. As a result, the SAS generation process didn't use the `LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCESS_KEY` to generate service SAS, but tried to generate user delegation SAS, which failed.
I'm in the process of validating that the user delegation SAS flow is correct. If it's not, I'll reopen the issue or fix it on a different one.

**Comment by ozkatz** [comment]
Thanks @Jonathan-Rosenberg! So how did setting `LAKEFS_BLOCKSTORE_AZURE_PRE_SIGNED_EXPIRY` to a longer period worked around that?

**Comment by ozkatz** [comment]
Well I managed to get it working with that setting and the command I wrote above. I recall that before setting the additional environment variable, I did in fact got an outdated presigned URL

**Comment by Jonathan-Rosenberg** [comment]
As you wrote, it might be a different bug. Currently, this env var isn't set and it does work.
I'm not sure which env vars were used when you worked with this lakeFS instance.
