### ISSUE TITLE
[Bug]: Quickstart is broken when creating sample repo

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6674]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Run the container: `docker run --name lakefs --pull always \
             --rm --publish 8000:8000 \
             treeverse/lakefs:latest \
             run --quickstart`
2. Open the UI and login
3. Click `Create Sample Repository`

![image](https://github.com/treeverse/lakeFS/assets/9861474/688f23b8-e13e-430a-bc4c-5ef22be39b56)

### Expected behavior

Sample repo is created successfully. 

### lakeFS version

0.111.0

### How lakeFS is installed

docker, local

### Relevant log output

```shell
2023/10/02 08:07:01 http: panic serving 172.17.0.1:50112: assignment to entry in nil map
goroutine 303 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xb0
panic({0x166c8a0, 0x4ebed40})
	/usr/local/go/src/runtime/panic.go:890 +0x248
github.com/treeverse/lakefs/pkg/samplerepo.AddBranchProtection({0x4ee1b30, 0x400e4e8060}, 0x400e1db9a0, {0x4f0a040, 0x40003aa820})
	/build/pkg/samplerepo/samplecontent.go:126 +0xe0
github.com/treeverse/lakefs/pkg/api.(*Controller).CreateRepository(0x400047a380, {0x4edeca0, 0x400e1ad818}, 0x400e1e7e00, {0x400e48b1e0, {0x400e4e2210, 0xa}, 0x400e4e220c, {0x400e0bbec0, 0x12}}, ...)
	/build/pkg/api/controller.go:1623 +0x89c
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository.func1({0x4edeca0?, 0x400e1ad818?}, 0x1980001?)
	/build/pkg/api/apigen/lakefs.gen.go:20518 +0x68
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository(0x400c6bcba0, {0x4edeca0, 0x400e1ad818}, 0x400e1e7d00)
	/build/pkg/api/apigen/lakefs.gen.go:20525 +0x4ac
net/http.HandlerFunc.ServeHTTP(0x400cc86910?, {0x4edeca0?, 0x400e1ad818?}, 0xffffbc338108?)
	/usr/local/go/src/net/http/server.go:2122 +0x38
....
```
```


### Contact details

_No response_

**Comment by N-o-Z** [comment]
This does not only affect quickstart - creation of samples repo is broken
