### ISSUE TITLE
Flakiness in blockstore unit tests

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6811]
Run Go tests fails sometimes while running block's gs tests:

```
2023/10/18 09:12:23 Could not create bucket 'bucket1': Post "http://127.0.0.1:4443/storage/v1/b?alt=json&prettyPrint=false&project=testProject": EOF
FAIL	github.com/treeverse/lakefs/pkg/block/gs	2.251s
```

EDIT (@johnnyaug): Something similar happens in Azure:
```
ok  	github.com/treeverse/lakefs/pkg/block	0.037s	coverage: 65.2% of statements
panic: Put "http://account1.azurite.test:32770/container1?restype=container": EOF

goroutine 1 [running]:
github.com/treeverse/lakefs/pkg/block/azure_test.runAzurite(0xc0004449c0)
	/home/runner/work/lakeFS/lakeFS/pkg/block/azure/main_test.go:95 +0x5b1
github.com/treeverse/lakefs/pkg/block/azure_test.TestMain(0x141b541?)
	/home/runner/work/lakeFS/lakeFS/pkg/block/azure/main_test.go:109 +0xfe
main.main()
	_testmain.go:86 +0x33e
FAIL	github.com/treeverse/lakefs/pkg/block/azure	18.027s
2023/10/24 08:14:52 Could not create bucket 'bucket1': Post "http://127.0.0.1:4443/storage/v1/b?alt=json&prettyPrint=false&project=testProject": EOF
```

**Comment by Isan-Rivkin** [comment]
Potentially linked issue with Azure: #6849
