### ISSUE TITLE
Unit tests: Azure block adapter unit test sporadically fails

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6849]
Noticed this test started to fail occasionally after we upgraded the Azurite version (not sure if related)

https://github.com/treeverse/lakeFS/actions/runs/6624090114/job/17992371450?pr=6837

```
ok  	github.com/treeverse/lakefs/pkg/block	0.037s	coverage: 65.2% of statements
panic: Put "http://account1.azurite.test:32770/container1?restype=container": EOF

goroutine 1 [running]:
github.com/treeverse/lakefs/pkg/block/azure_test.runAzurite(0xc0004449c0)
	/home/runner/work/lakeFS/lakeFS/pkg/block/azure/main_test.go:95 +0x5b1
github.com/treeverse/lakefs/pkg/block/azure_test.TestMain(0x141b541?)
	/home/runner/work/lakeFS/lakeFS/pkg/block/azure/main_test.go:109 +0xfe
main.main()
	_testmain.go:86 +0x33e
FAIL	github.com/treeverse/lakefs/pkg/block/azure	18.027s
2023/10/24 08:14:52 Could not create bucket 'bucket1': Post "http://127.0.0.1:4443/storage/v1/b?alt=json&prettyPrint=false&project=testProject": EOF
```

**Comment by N-o-Z** [comment]
preceded  by https://github.com/treeverse/lakeFS/issues/6811
