### ISSUE TITLE
Spark metadata client fails on DataBricks 12.2 LTS

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#7289]
User reporting an issue running the Spark metadata client on DataBricks 12.2 LTS.  Error backtrace includes the line
> ```
> Caused by: java.lang.ClassCastException: com.google.protobuf.timestamp.Timestamp cannot be cast to scalapb.Message
> ```
when deserializing a catalog Entry.  (I can probably furnish more stacktrace lines if needed.)

This prevents them from using the metadata client code.

**Comment by arielshaqed** [comment]
I _suspect_ this is another shadowing or similar issue.

## Background

Protocol buffers can be difficult.  In Scala you essentially _have_ to use com.thesamet.scalapb, which brings its own protobuf implementation with it.  This is especially true in hosted environments like DataBricks, where we might be getting a _different_ version of any package than expected.

## Possible paths to solution

Assuming we can reproduce the issue, I would try _either_ to remove shading of com.google.protobuf in clients/spark/build.sbt _or_ to add shading of com.thesamet.scalapb _or_ to bump its version.  The last 2 are probably safer choices.

**Comment by arielshaqed** [comment]
Reproduced on a 12.2 LTS cluster of my own.  Full stacktrace:
```java
java.lang.ClassCastException: com.google.protobuf.timestamp.Timestamp cannot be cast to scalapb.Message
	at io.treeverse.lakefs.catalog.Entry.mergeFrom(Entry.scala:120)
	at io.treeverse.lakefs.catalog.Entry.mergeFrom(Entry.scala:9)
	at scalapb.LiteParser$.parseFrom(LiteParser.scala:12)
	at scalapb.GeneratedMessageCompanion.parseFrom(GeneratedMessageCompanion.scala:195)
	at scalapb.GeneratedMessageCompanion.parseFrom$(GeneratedMessageCompanion.scala:195)
	at io.treeverse.lakefs.catalog.Entry$.parseFrom(Entry.scala:189)
	at io.treeverse.clients.SSTableIterator.next(SSTableReader.scala:52)
	at io.treeverse.clients.SSTableIterator.next(SSTableReader.scala:24)
	at io.treeverse.clients.EntryRecordReader.nextKeyValue(LakeFSInputFormat.scala:118)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:257)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:761)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:82)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:208)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:179)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:142)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:41)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:99)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:104)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:103)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:142)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:904)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1740)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:907)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by arielshaqed** [comment]
## Workaround

Use this assembled package: s3://treeverse-clients-us-east/lakefs-spark-client/0.13.0-RC.1/lakefs-spark-client-assembly-0.13.0-RC.1.jar

This might well be the solution for this issue, and I opened #7299 for a thorough solution.
