### ISSUE TITLE
[Bug]: docs preview is broken 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#7632]
### What happened?

Running make docs-serve prints the error message, not allowing to test docs changes locally. 

### Expected behavior

Have a locally available docs server

### lakeFS version

latest dev

### How lakeFS is installed

locally

### Relevant log output

```shell
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll/configuration.rb:157:in `config_files'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll.rb:113:in `configuration'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:89:in `start'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/jekyll:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:25:in `load'
	from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
make: *** [docs-serve] Error 1
```

**Comment by itaiad200** [comment]
Works now.
